**Chapter** 3. 파이썬과 코딩의 기초

# 3.1 계산식, 라이브러리와 함수 ~ 3.4 변수


In [ ]:
'''
실행 단축키
1. ctrl + Enter
2. shift + Enter -> 셀 바꿈!
'''

In [ ]:
3*4

12

In [ ]:
24//7 # 정수 나눗셈

3

In [ ]:
25%7 # 나머지

4

In [ ]:
2**3

8

In [ ]:
import numpy as np
np.cos(3.141592)

-0.9999999999997864

In [ ]:
!pip install numpy
# ! = Linux 명령어 사용하라!

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# from 라이브러리명 import 함수명
from numpy import cos

In [ ]:
# 연습문제 4 (p.108)
# (1)
np.sin(np.pi/3)+np.cos(np.pi/3)

1.3660254037844388

In [ ]:
a = np.cos(3.14)
print(a)

-0.9999987317275395


In [ ]:
a = 3 # int
a = 3.4 # float
type(a)
# print(a)

float

In [ ]:
a = 3==4
print(a)

False


In [ ]:
# 연습문제 3 (p119)
radius = 4.53
np.pi * (radius**2) * 30 / 360

5.372359057087565

In [ ]:
# 연습문제 6
100 * (1 + 0.019) * (1 + 0.019)

103.83609999999999

In [ ]:
# 연습문제 1
total = 1200 * 36
print(total)

43200


In [ ]:
# 연습문제 2
r = 4.5312
size_area = np.pi * (r**2)
print(size_area)

64.50246860427404


In [ ]:
# np.round(3.567, 1) # 3.6
np.round(1, 3.567)

TypeError: ignored

In [ ]:
# def round_(a, decimals=0, out=None)
np.round(decimals=1, a=3.567)

3.6

In [ ]:
import numpy as np
s = np.sin(np.pi/3)

# 3.5 함수

In [ ]:
a = 'b ='
b = 3.5
print(a,b)

b = 3.5


In [ ]:
print(a+str(b))

b =3.5


In [ ]:
a = '3.5'
b = float(a) + 1
print(b)

4.5


In [ ]:
np.round(3.5)

4.0

In [ ]:
a = 3.5
int(a)

3

In [ ]:
# 실습
v = 0.5

In [ ]:
import numpy as np
s = np.sin(0.5)
c = np.cos(0.5)
print(s+c)
print(s-c)

print(np.round(s+c,3))
print(np.round(s-c,3))

1.3570081004945758
-0.39815702328616975
1.357
-0.398


In [ ]:
result1 = np.round(s+c,3)
result2 = np.round(s-c,3)

print(f'sin(0.5)+cos(0.5)={result1}')
print(f'sin(0.5)-cos(0.5)={result2}')

sin(0.5)+cos(0.5)=1.357
sin(0.5)-cos(0.5)=-0.398


In [ ]:
gpa = '4.3'

In [ ]:
gpa = float(gpa) * 100 / 4.5
print(gpa)

95.55555555555556


In [ ]:
s = 3.4
type(s)

float

In [ ]:
type(v)

int

In [ ]:
v = int(s)
type(v)

int

In [ ]:
v = str(s)
type(v)

str

In [ ]:
print(v)

3.4


In [ ]:
v + 3

TypeError: ignored

In [ ]:
v + 'Korea'

'3.4Korea'

In [ ]:
st = f'Value of s is {s}'

In [ ]:
st

'Value of s is 3.4'

In [ ]:
print(f's의 값은 {s} 입니다.')

s의 값은 3.4 입니다.


In [ ]:
# p126
# 연습문제 1
v = 0.5

In [ ]:
import numpy as np
s = np.sin(0.5)

In [ ]:
c = np.cos(0.5)

In [ ]:
print(s+c)

1.3570081004945758


In [ ]:
print(s-c)

-0.39815702328616975


In [ ]:
#  연습문제 5
year = 2022
month = 4
day = 5

In [ ]:
print(f'{year}년 {month}월 {day}일')

2022년 4월 5일


# 3.6 조건문

In [ ]:
import numpy as np
a = np.sin(np.pi/3)
print(f'결과는 {a:.2f} 입니다.')
print(f'결과는 {a:.4f} 입니다.')
print('사인값은 ', end='') # 줄바꿈 X
if a > 0:
  print('양수임')
else:
  print('양수가 아님')

결과는 0.87 입니다.
결과는 0.8660 입니다.
사인값은 양수임


In [ ]:
# p.136
x, y = map(int, input().split())
place = 0

if x > 0 and y > 0:
  place = 1
elif x < 0 and y > 0:
  place = 2
elif x < 0 and y < 0:
  place = 3
elif x > 0 and y < 0:
  place = 4

if place==0:
  print('점이 축 위에 있습니다')
else:
  print(f'점은 {place}사분면에 있습니다.')

4 -2
점은 4사분면에 있습니다.


In [ ]:
# p.138
x = int(input())

def a(x):
  if x%2 == 0:
    x *= 2
  else:
    x /= 2
  return x

23


In [ ]:
a(x)

11.5

In [ ]:
v = -1.5

In [ ]:
import numpy as np
v = np.sin(v)

if v > 0:
  say = 'PLUS'
elif v < 0:
  say = 'MINUS'
else: # v == 0
  say = 'ZERO'

print(say)

MINUS


In [ ]:
score = 85

if score >= 90:
  grade = 'A'
elif score >= 80 and score < 90:
  grade = 'B'
elif score >= 70 and score < 80:
  grade = 'C'
elif score >= 60 and score < 70:
  grade = 'D'
else:
  grade = 'F'

print(grade)

B


In [ ]:
w = 65.3
h = 1.78

bmi = w / (h * h)

if bmi >= 25:
  status = '비만..'
elif bmi < 18.5:
  status = '저체중..'
else:
  status = '정상'

In [ ]:
# p.139
# 연습문제 3
score = 85

if score >= 90:
  print('A')
elif score >= 80:
  print('B')
elif score >= 70:
  print('C')
elif score >= 60:
  print('D')
else:
  print('F')

B


In [ ]:
# p.140
# # 연습문제 4
weight, height = map(float, input().split())

bmi = weight / (height * height)

print(f'님의 bmi는 {bmi: .3f}, ', end='')
if bmi >= 25:
  print('비만')
elif bmi < 18.5:
  print('저체중')
else:
  print('정상')

49.5 1.52
님의 bmi는  21.425, 정상


In [ ]:
# 연습문제 5
grade = 'A'

score = 0
if grade == 'A':
  score = 95
elif grade == 'B':
  score = 95
elif grade == 'C':
  score = 76
elif grade == 'D':
  score = 65

print(f'The converted score is {score}')

The converted score is 95


In [ ]:
# p.143
# 연습문제 4
number_of_purchases = 15
total_amount_of_purchases = 150000
price_item = 5000

if number_of_purchases >= 10 and total_amount_of_purchases >= 100000:
  print('VIP')
  price_item -= (price_item * 0.1)
elif number_of_purchases >= 1:
  price_item -= (price_item * 0.05)

print(f'최종 : {price_item}')

VIP
최종 : 4500.0


In [ ]:
# p.145
# 연습문제 6
a = 93
b = 54
c = 65
d = 68

total = (a+b+c+d) / 4

print(f'평균 : {total}')
if a >= 60 and b >= 60 and c >= 60 and d >= 60:
  if total >= 70:
    print('합')
  else:
    print('불합')
else:
    print('과락..불합')

평균 : 70.0
과락..불합


# 3.7 고급 데이터 타입



In [ ]:
vs = [1,3,'Hi',8,5]

In [ ]:
vt = vs

In [ ]:
vt

[1, 3, 'Hi', 8, 5]

In [ ]:
vt[3] = -5
print(vs)

[1, 3, 'Hi', -5, 5]


In [ ]:
v = range(3,9)
print(v, type(v))

v1 = list(range(3,9))
print(v1, type(v1))

range(3, 9) <class 'range'>
[3, 4, 5, 6, 7, 8] <class 'list'>


In [ ]:
vs.append(999)

In [ ]:
print(vs)

[3, 'Hi', 8, 5, 999, 'A']


In [ ]:
vs.pop(0)

'A'

In [ ]:
vs.append('A')

In [ ]:
vs.insert(1,'B')

In [ ]:
print(vs)

['B', 'Hi', 8, 5, 999, 'A']


In [ ]:
len(vs)

6

In [ ]:
vs[1:5]

['Hi', 8, 5, 999]

In [ ]:
vt = []

In [ ]:
vs[3] = 4

In [ ]:
print(vt)

[]


In [ ]:
print(vs)

['B', 'Hi', 8, 4, 999, 'A']


In [ ]:
a = range(3)

In [ ]:
print(a)
type(a)

range(0, 3)


range

In [ ]:
list(a)

[0, 1, 2]

In [ ]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [ ]:
a = (3,4,5)
print(a[0])

3


In [ ]:
tup = 3,4,5
print(tup[0])

3


In [ ]:
list1 = [5,8,7]
tup = tuple(list1)

In [ ]:
tup

(5, 8, 7)

In [ ]:
tup[2] = 1

TypeError: ignored

In [ ]:
b = a

In [ ]:
d1 = {'Title':'우리가 빛의 속도로 갈 수 없다면',
      'Year':2019,
      'Author':'Kim Cho-yeop',
      'Country':'Korea',
      'Genere':'SF'
      }

In [ ]:
d1['Title']

'우리가 빛의 속도로 갈 수 없다면'

In [ ]:
d2 = {'Title':'불편한 편의점',
      'Year':2019,
      'Author':'장호연..?',
      'Country':'Korea',
      'Genere':'Novel..'
      }

In [ ]:
d3 = {'Title':'천개의 파랑',
      'Year':2021,
      'Author':'천선란',
      'Country':'Korea',
      'Genere':'SF'
      }

In [ ]:
# 딕셔너리의 리스트 생성
d_list	=	[d1,d2,d3]

In [ ]:
# 내용 확인
print(d_list[1]['Title'])

불편한 편의점


In [ ]:
for i in range(3):
  if d_list[i]['Year'] < 2020:
    print(d_list[i])

{'Title': '우리가 빛의 속도로 갈 수 없다면', 'Year': 2019, 'Author': 'Kim Cho-yeop', 'Country': 'Korea', 'Genere': 'SF'}
{'Title': '불편한 편의점', 'Year': 2019, 'Author': '장호연..?', 'Country': 'Korea', 'Genere': 'Novel..'}


In [ ]:
d_list2 = d_list

In [ ]:
d_list[1]['Year'] = 2023
print(d_list[1])

{'Title': '불편한 편의점', 'Year': 2023, 'Author': '장호연..?', 'Country': 'Korea', 'Genere': 'Novel..'}


In [ ]:
s = {3, 5, 4}
print(s, type(s))

{3, 4, 5} <class 'set'>


In [ ]:
# 집합 (p.153) 실습
v = [3,4,5,6]
avg = (v[0] + v[1] + v[2] + v[3]) / 4
print(avg)

4.5


In [ ]:
v = list(range(1, 30, 2))
print(v[14])

29


In [ ]:
dict1 = {'KO' : '사랑', 'EN' : 'Love', 'JP' : '愛'}
dict2 = {'KO' : '집', 'EN' : 'House', 'JP' : '家'}
dict3 = {'KO' : '바다', 'EN' : 'Sea', 'JP' : '海'}

In [ ]:
dict_list = []
dict_list.append(dict1)
dict_list.append(dict2)
dict_list.append(dict3)

print(dict_list)

[{'KO': '사랑', 'EN': 'Love', 'JP': '愛'}, {'KO': '집', 'EN': 'House', 'JP': '家'}, {'KO': '바다', 'EN': 'Sea', 'JP': '海'}]


In [ ]:
dict_list[1]['EN']

'House'

In [ ]:
dict_list[2]['KO']

'바다'

# 3.8 반복문

In [ ]:
data_list = list(range(1,11))
sum = 0

for x in data_list:
# for x in range(1,11):
  sum += x

print(sum)

55


In [ ]:
v = list(range(3,7))
sum = 0
for n in v:
  sum += n
avg = sum / len(v)

avg

4.5

In [ ]:
import numpy as np
n = 0       # 승수
result = 1  # 2**n

while result <= 10000:
  n += 1
  result *= 2

print(f'The answer is {result//2}')

The answer is 8192


In [ ]:
for n in range(10000):
  result = 2**n
  if result>10000:
    break

print(f'The answer is {result//2}')

The answer is 8192


In [ ]:
customer = [{'Name' : 'Yujeong','Tel' : 9787, 'Price':18},
            {'Name' : 'Jaehyun','Tel' : 1997, 'Price':214},
            {'Name' : 'Taeil','Tel' : 1994, 'Price':614},
            {'Name' : 'Haechan','Tel' : 2000, 'Price':66}]

for c in customer:
  if c['Price'] > 100:
    print(c)

{'Name': 'Jaehyun', 'Tel': 1997, 'Price': 214}
{'Name': 'Taeil', 'Tel': 1994, 'Price': 614}


In [ ]:
for n in range(101):
  if n % 3 != 0:
    print(n, end=' ')

1 2 4 5 7 8 10 11 13 14 16 17 19 20 22 23 25 26 28 29 31 32 34 35 37 38 40 41 43 44 46 47 49 50 52 53 55 56 58 59 61 62 64 65 67 68 70 71 73 74 76 77 79 80 82 83 85 86 88 89 91 92 94 95 97 98 100 

In [ ]:
for i in range(1, 10):
  sq_type = np.sqrt(i)
  print(sq_type)
  if sq_type == int(sq_type):
    print(f'{i} = {int(sq_type)} * {int(sq_type)}')
    # print(i, end = ' ')

1.0
1 = 1 * 1
1.4142135623730951
1.7320508075688772
2.0
4 = 2 * 2
2.23606797749979
2.449489742783178
2.6457513110645907
2.8284271247461903
3.0
9 = 3 * 3


In [ ]:
s = np.sqrt(5)
type(s)

numpy.float64

In [ ]:
# for x in [1,2,3,4,5]:
for x in range(1,6):
  print(x)

1
2
3
4
5


In [ ]:
x_list = [3,4,8,6,9,-3]
# for i in range(6):
# for i in range(len(x_list)):
for i in x_list:
  print(i)

3
4
8
6
9
-3


In [ ]:
n = int(input())
cnt = 0
print('------')
while n != 1:
  if n % 2 == 0:
    n //= 2
  else:
    n = n*3+1
  cnt += 1
  print(n)

print( f'콜라츠 추측이 {cnt}번 만에 성립!')


5
------
16
8
4
2
1
콜라츠 추측이 5번 만에 성립!


In [ ]:
# p.165
v = [3,4,5,6]

In [ ]:
sum = 0
for x in v:
  sum += x
avg = sum / len(v)

In [ ]:
print(avg)

4.5


In [ ]:
n = 0
power_of_n = 1

while power_of_n <= 10000:
  n += 1
  power_of_n *= 2

print(f'The answer is {power_of_n//2}')

The answer is 8192


In [ ]:
2**14

16384

In [ ]:
2**13

8192

# 3.9 Numpy 배열

In [ ]:
import numpy as np

In [ ]:
n_list = [[3,4,1,2],[8,2,4,9]]
n = np.array(n_list)

In [ ]:
n_list[0][2]

1

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
n = np.ones((3,5))

In [ ]:
n[2,4] = 100

In [ ]:
n

array([[  1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1., 100.]])

In [ ]:
n = np.random.rand(3,5)

In [ ]:
n

array([[0.61655598, 0.25288403, 0.10133691, 0.0165047 , 0.3052975 ],
       [0.45166636, 0.23181334, 0.34273956, 0.33146903, 0.60246115],
       [0.84521762, 0.31741332, 0.92474468, 0.52678471, 0.85425075]])

In [ ]:
n[1,1]

0.44065211798415016

In [ ]:
n = int(n * 10)

TypeError: ignored

In [ ]:
n = np.round(n*10)

In [ ]:
n

array([[6., 3., 1., 0., 3.],
       [5., 2., 3., 3., 6.],
       [8., 3., 9., 5., 9.]])

In [ ]:
n[1,2]

4.0

In [ ]:
n[1,2:4]

array([4., 7.])

In [ ]:
n[1,2:]

array([4., 7., 3.])

In [ ]:
n[1:,2:]

array([[4., 7., 3.],
       [5., 8., 5.]])

In [ ]:
n[:2,2:]

array([[8., 5., 6.],
       [4., 7., 3.]])

In [ ]:
# 변수명[start:end:step]
n[:,::2]
# 행 = 전체
# 열 = 0 ~ 2, 0+2

array([[3., 8., 6.],
       [6., 4., 3.],
       [7., 5., 5.]])

In [ ]:
b = np.array([[True,False,True,False,True],
              [True,False,True,False,True],
              [True,False,False,False,False]])

In [ ]:
b

array([[ True, False,  True, False,  True],
       [ True, False,  True, False,  True],
       [ True, False, False, False, False]])

In [ ]:
n[b]
# n에서 b의 값이 True인 셀만 선택됨

array([3., 8., 6., 6., 4., 3., 7.])

In [ ]:
n

array([[3., 6., 8., 5., 6.],
       [6., 4., 4., 7., 3.],
       [7., 4., 5., 8., 5.]])

In [ ]:
n[b] = 0

In [ ]:
n

array([[ 1.,  7.,  0.,  5.,  9.],
       [10.,  0.,  1.,  6.,  9.],
       [ 0.,  1.,  6.,  5.,  1.]])

In [ ]:
b = n > 3

In [ ]:
b

array([[False,  True, False,  True,  True],
       [ True, False, False,  True,  True],
       [False, False,  True,  True, False]])

In [ ]:
n[b] = 0

In [ ]:
n

array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1.]])

In [ ]:
n[n>3] = 1000

In [ ]:
n

array([[1000.,    3.,    1.,    0.,    3.],
       [1000.,    2.,    3.,    3., 1000.],
       [1000.,    3., 1000., 1000., 1000.]])

In [ ]:
# 연습문제 4
n = 0
max = 1
while 5*(n**3)+2*(n**2)-(19*n)+20 < 20000:
    n += 1
    if max < n:
      max = n

print(max)

16


In [ ]:
# 연습문제 7
lot_ans = (16,9,7,21,43,14)
lot_me = (1,9,3,4,5,14)

cnt = 0

for x in range(6):
  if lot_ans[x] == lot_me[x]:
    cnt+=1
print(cnt)

2


In [ ]:
import numpy as np

In [ ]:
n = np.round(np.random.rand(3,4)*10.0)

In [ ]:
n.shape
# (column, row)

(3, 4)

In [ ]:
n

array([[ 3.,  2.,  1.,  9.],
       [ 4.,  1.,  8., 10.],
       [ 1.,  1.,  6.,  6.]])

In [ ]:
m = np.expand_dims(n,2)

In [ ]:
m.shape

(3, 4, 1)

In [ ]:
m = np.expand_dims(n,0)

In [ ]:
m.shape

(1, 3, 4)

In [ ]:
m = np.expand_dims(n,-1)

In [ ]:
m.shape

(3, 4, 1)

In [ ]:
m

array([[[ 3.],
        [ 2.],
        [ 1.],
        [ 9.]],

       [[ 4.],
        [ 1.],
        [ 8.],
        [10.]],

       [[ 1.],
        [ 1.],
        [ 6.],
        [ 6.]]])

In [ ]:
n

array([[ 3.,  2.,  1.,  9.],
       [ 4.,  1.,  8., 10.],
       [ 1.,  1.,  6.,  6.]])

In [ ]:
m = n.reshape(12)

In [ ]:
m

array([ 3.,  2.,  1.,  9.,  4.,  1.,  8., 10.,  1.,  1.,  6.,  6.])

In [ ]:
m.reshape(3,4)

array([[ 3.,  2.,  1.,  9.],
       [ 4.,  1.,  8., 10.],
       [ 1.,  1.,  6.,  6.]])

In [ ]:
m.reshape(4,3)
# m.reshape(4,-1)
# row는 auto fix

array([[ 3.,  2.,  1.],
       [ 9.,  4.,  1.],
       [ 8., 10.,  1.],
       [ 1.,  6.,  6.]])

In [ ]:
k = m.reshape((2,3,-1)) # tuple로 작성

In [ ]:
k.shape

(2, 3, 2)

In [ ]:
n = np.round(np.random.rand(3,4)*10.0)

In [ ]:
n

array([[ 8.,  9.,  5.,  5.],
       [10.,  2.,  9.,  9.],
       [ 4.,  2.,  8.,  3.]])

In [ ]:
np.max(n)

10.0

In [ ]:
np.sum(n)/(n.shape[0]*n.shape[1])

6.166666666666667

In [ ]:
data = np.array([[8.5, 200, 60.2, 450.3, 50],
                 [12.3, 230.5, 56.3, 390.2, 35],
                 [9.2, 190, 30, 500.4, 60]])

In [ ]:
mean_v = np.mean(data, axis=0)
std_v = np.std(data, axis=0)
print(f'50m달리기: {mean_v[0]:.2f}±{std_v[0]:.2f}')
print(f'멀리뛰기: {mean_v[1]:.2f}±{std_v[1]:.2f}')
print(f'오래매달리기: {mean_v[2]:.2f}±{std_v[2]:.2f}')
print(f'오래달리기: {mean_v[3]:.2f}±{std_v[3]:.2f}')
print(f'윗몸일으키기: {mean_v[4]:.2f}±{std_v[4]:.2f}')

50m달리기: 10.00±1.65
멀리뛰기: 206.83±17.23
오래매달리기: 48.83±13.41
오래달리기: 446.97±45.05
윗몸일으키기: 48.33±10.27


In [ ]:
data = np.array([1,2,5,0,1])
idx_max = np.argmax(data)
idx_min = np.argmin(data)
print(f'최솟값은 {data[idx_min]}입니다.')
print(f'최댓값은 {data[idx_max]}입니다.')

최솟값은 0입니다.
최댓값은 5입니다.


In [ ]:
data = np.array([[8.5, 200, 60.2, 450.3, 50],
                 [12.3, 230.5, 56.3, 390.2, 35],
                 [9.2, 190, 30, 500.4, 60]])

In [ ]:
data.max(0)

array([ 12.3, 230.5,  60.2, 500.4,  60. ])

In [ ]:
data.min(0)

array([  8.5, 190. ,  30. , 390.2,  35. ])

In [ ]:
idx_min = np.argmin(data, axis=0)
# 반환값 = 최솟값의 인덱스

In [ ]:
idx_min[0]

0

In [ ]:
best_50m_idx = idx_min[0]
long_jump_of_best_50m_person = data[best_50m_idx, 1]

In [ ]:
print(f'50m에서 가장 빠른 기록보유자는 {best_50m_idx}번 입니다.')
print(f'해당 멀리뛰기 기록은 {long_jump_of_best_50m_person}입니다.')

50m에서 가장 빠른 기록보유자는 0번 입니다.
해당 멀리뛰기 기록은 200.0입니다.


In [ ]:
data[:,1]

array([200. , 230.5, 190. ])

In [ ]:
b_sel = data[:,1] > 190

In [ ]:
b_sel

array([ True,  True, False])

In [ ]:
data_sel = data[b_sel,:]

In [ ]:
data_sel

array([[  8.5, 200. ,  60.2, 450.3,  50. ],
       [ 12.3, 230.5,  56.3, 390.2,  35. ]])

In [ ]:
data[b_sel, 4]

array([50., 35.])

In [ ]:
data.reshape(5,3)

array([[  8.5, 200. ,  60.2],
       [450.3,  50. ,  12.3],
       [230.5,  56.3, 390.2],
       [ 35. ,   9.2, 190. ],
       [ 30. , 500.4,  60. ]])

In [ ]:
# 연습문제 4 ~ 7
n = np.round(np.random.rand(45))

In [ ]:
n

array([0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0.])

In [ ]:
n = n.reshape(9,5)
# n.reshape(9, -1)

In [ ]:
n

array([[0., 0., 0., 1., 1.],
       [0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [1., 1., 1., 0., 0.],
       [0., 1., 1., 0., 1.],
       [0., 1., 1., 0., 0.]])

In [ ]:
m = np.expand_dims(n,axis=-1)

In [ ]:
m.shape

(9, 5, 1)

In [ ]:
# 오래매달리기 40초 이상인 학생들의
# 윗몸일으키기 횟수의 평균
data[data[:,2] >= 40, 4].mean()

42.5

In [ ]:
# 오래달기 기록 중 400초 이상은 모두 400초로 수정
b_sel = data[:,3] >= 400
print(b_sel)

[ True False  True]


In [ ]:
data[data[:,3] >= 400.3] = 400

In [ ]:
data[:,3]

array([400. , 390.2, 400. ])

In [ ]:
'''
실습 다시 해보자고
'''

In [ ]:
import numpy as np
n = np.array([ [3,4,1,2],
              [8,2,4,9],
              [2,1,8,7] ])
b = np.array([ [True, False, True, False],
              [True, False, True, False],
              [True, False, True,False] ])

In [ ]:
n[b] = 0
print(n)

[[0 4 0 2]
 [0 2 0 9]
 [0 1 0 7]]


In [ ]:
n[n<5] = 0
print(n)

[[0 0 0 0]
 [8 0 0 9]
 [0 0 8 7]]


In [ ]:
m = np.array([ [3,4,1,2],
              [8,2,4,9],
              [2,1,8,7] ])
print(n<5)

[[ True  True  True  True]
 [False  True  True False]
 [ True  True False False]]


In [ ]:
n = np.zeros(3)
n

array([0., 0., 0.])

In [ ]:
n = np.expand_dims(n, 1)
n

array([[0.],
       [0.],
       [0.]])

In [ ]:
n = np.array([3,4,1,2,8,2,4,9])

In [ ]:
m = np.reshape(n, (2,4))
print(n)
print(n.shape)
print(m)
print(m.shape)

[3 4 1 2 8 2 4 9]
(8,)
[[3 4 1 2]
 [8 2 4 9]]
(2, 4)


In [ ]:
m.shape[0]

2

In [ ]:
m.shape[1]

4

In [ ]:
m = n.reshape((4,2))

In [ ]:
m

array([[3, 4],
       [1, 2],
       [8, 2],
       [4, 9]])

In [ ]:
m = n.reshape((-1, 4))

In [ ]:
m

array([[3, 4, 1, 2],
       [8, 2, 4, 9]])

In [ ]:
n = np.array([3,4,1,2,8,2,4,9])

n[0:3]

array([3, 4, 1])

In [ ]:
n[1:6:2]

array([4, 2, 2])

In [ ]:
n[1:6:2] = [-1,-2,-3]

In [ ]:
n

array([ 3, -1,  1, -2,  8, -3,  4,  9])

In [ ]:
n[1:6:2] = [-1,-2]

ValueError: ignored

In [ ]:
print(n[:3])
print(n[3:])

[ 3 -1  1]
[-2  8 -3  4  9]


In [ ]:
n = np.array([ [3,4,1,2], [8,2,4,9], [2,1,8,7]])
n[1:,:2]

array([[8, 2],
       [2, 1]])

In [ ]:
n[1:, :]

array([[8, 2, 4, 9],
       [2, 1, 8, 7]])

In [ ]:
m = n[1:, :2]
m[0, :] = 0
print(n)

[[3 4 1 2]
 [0 0 4 9]
 [2 1 8 7]]


# 3.10 사용자 정의 함수

In [ ]:
def add():
  s = a + b
  return s

In [ ]:
a = 4
b = 5
c = add()
print(c)

9


In [ ]:
import numpy as np

In [ ]:
def change_var(arr):
  arr[0,0] = 999

In [ ]:
d = np.random.rand(5,4)
print(f'Before:{d[0,0]}')
change_var(d)
print(f'After:{d[0,0]}')

Before:0.052136012574577006
After:999.0


In [ ]:
def change_var(arr):
  arr = 999

In [ ]:
d = 'Korea'
print(f'Before:{d}')
change_var(d)
print(f'After:{d}')

Before:Korea
After:Korea


In [ ]:
d = (4,5)
print(f'Before:{d}')
change_var(d)
print(f'After:{d}')

Before:(4, 5)
After:(4, 5)


In [ ]:
# 연습문제 2
# 교수님 풀이이
data = 1000 + np.round(np.random.rand(30)*3000)


In [ ]:
data

array([2253., 1861., 2497., 2560., 3731., 3905., 1076., 3493., 1676.,
       1836., 1901., 1175., 3236., 2436., 3034., 3089., 3147., 1323.,
       1015., 2806., 3066., 3665., 2565., 2483., 3028., 1407., 2671.,
       1598., 1170., 3052.])

In [ ]:
def walk_prof(n):
  avg = np.mean(walk_prof)
  min_walk_day = np.argmin(data)
  min = n[min_walk_day]
  max_walk_day = np.argmax(data)
  max = n[max_walk_day]
  return avg, min_walk_day+1, min, max_walk_day+1, max

In [ ]:
# 내 풀이
def walk(arr):
  avg = np.mean(arr)
  min_day = np.argmin(arr)
  min = arr[min_day]
  max_day = np.argmax(arr)
  max = arr[max_day]
  return avg, min_day+1, min, max_day+1, max

In [ ]:
n = np.round(np.random.rand(30)*3000)

In [ ]:
n

array([ 315.,   91., 2739.,  684.,  841., 2134.,   28., 1919., 2584.,
        751., 1245.,  279., 1632., 2075., 1606., 1569.,  142.,  792.,
        765.,  784., 1532.,  898., 2302., 2071., 1877., 1932., 2794.,
        972., 1003.,  181.])

In [ ]:
walk(n)

(1284.5666666666666, 7, 28.0, 27, 2794.0)