# 3.2 (p.100)

In [ ]:
# 연습문제 3
pi = 3.141592
r = 6371
2 * pi * r

40030.165264

In [ ]:
# 연습문제 4
km = 390.5
h = 4.5
km / h

86.77777777777777

# 3.3 계산식, 라이브러리와 함수 (p.107)

In [ ]:
# 연습문제 1
import numpy as np

In [ ]:
np.sin(np.pi/4)

0.7071067811865475

In [ ]:
np.arcsin(0.5)

0.5235987755982989

In [ ]:
np.tan(np.pi/4)

0.9999999999999999

In [ ]:
np.arctan(0.7)

0.6107259643892086

In [ ]:
# 연습문제 2
np.sin(np.pi)

1.2246467991473532e-16

In [ ]:
np.arcsin(0.5)

0.5235987755982989

In [ ]:
np.exp(4)

54.598150033144236

In [ ]:
np.power(3,2)

9

In [ ]:
np.exp(4)

54.598150033144236

In [ ]:
np.log(2.7)

0.9932517730102834

In [ ]:
np.log10(10)

1.0

In [ ]:
np.sqrt(20)

4.47213595499958

In [ ]:
np.abs(-3.458)

3.458

In [ ]:
# 연습문제 3
print(256 / 38)
print(486 % 35)
print(129 * 356)
print((386 + 28) * 25)
print(2867 % 2)

6.7368421052631575
31
45924
10350
1


In [ ]:
# 연습문제 4
np.sin(np.pi/3)+np.cos(np.pi/3)

1.3660254037844388

In [ ]:
np.arcsin(-0.3) + np.arccos(1)

-0.3046926540153975

In [ ]:
np.log(7)/np.log(3)

1.7712437491614221

In [ ]:
np.sqrt(np.sqrt(15)+np.sqrt(26))

2.995330175423104

# 3.4 변수 (p.119)

In [ ]:
# 연습문제 1
total = 0
price = 1200 * 36
total += price
print(total)

43200


In [ ]:
# 연습문제 2
size_area = 0
r = 4.5312
size_area = np.pi * (r * r)
print(size_area)

64.50246860427404


In [ ]:
# 연습문제 3
radius = 4.53
width = np.pi * (radius**2) * 30 / 360
print(width)

5.372359057087565


In [ ]:
# 연습문제 4
cur_year = 2023
birth_year = 1997
age = cur_year - birth_year + 1
print(age)

27


In [ ]:
# 연습문제 5
mine = 'iPhone12'
capacity = 128
weight = 162
display = 15.4

In [ ]:
# 연습문제 6
100 * (1+0.019) ** 2

103.83609999999999

In [ ]:
100 * (1 + 0.019) * (1 + 0.019)

103.83609999999999

In [ ]:
# 연습문제 7
t = 26.5
f = t * 1.8 + 32
print(f)

79.7


# 3.5 함수 (p.129)

In [ ]:
# 연습문제 2
v = 0.25

In [ ]:
import numpy as np

In [ ]:
np.round(np.sin(v*2) + np.cos(v),3)

1.448

In [ ]:
np.round(np.sqrt(np.cos(v/2)-np.sin(v/2)),3)

0.931

In [ ]:
np.round(np.power(np.sin(v*3),4),3)

0.216

In [ ]:
np.round(abs(np.sin(v*3)-np.cos(v*6)),3)

0.611

In [ ]:
# 연습문제 3
a,b,c = 2,3,28
a * b * np.sin(c) / 2

0.8127173649236071

In [ ]:
# 연습문제 4
'''
원뿔의 옆넓이 면적...?
원넓이 + 부채꼴의 넓이
= (pi * r * r) + (1/2 * h * r)
'''

In [ ]:
# 연습문제 5
birth_year = '2002'
birth_month = '9'
birth_day = '3'

cur_year = '2022'
cur_month = '4'
cur_day = '3'

In [ ]:
age = int(cur_year) - int(birth_year) + 1

In [ ]:
print(age)

21


In [ ]:
# 연습문제 6
title = '지구 밖의 온실'
author = '김초엽'
published_year = 2021
price = 17000
total_page = 350
star_rating = 4.8

In [ ]:
print(f'책 제목 : {title}, 저자 : {author}, 출판연도 : {published_year}, 가격 : {price}. 페이지 수 : {total_page}, 평점 : {star_rating}')

책 제목 : 지구 밖의 온실, 저자 : 김초엽, 출판연도 : 2021, 가격 : 17000. 페이지 수 : 350, 평점 : 4.8


# 3.6 조건문

In [ ]:
# 연습문제 1
h = 178.3
w = 65.5

if h >= 150 or w >= 60:
  print('possible')
else:
  print('impossible')

possible


In [ ]:
# 연습문제 2
x = 5

if x > 0:
  print(np.sqrt(x))
else:
  print('허수')

2.23606797749979


In [ ]:
# 연습문제 3
a, b, c = 3, 4, 5

if a+b > c or a+c > b or b+c > a:
  print('존재쓰~')
else:
  print('노~')

존재쓰~


In [ ]:
# 연습문제 4
number_of_purchases = 10
total_amount_of_purchases = 150000
price_item = 5000

if number_of_purchases >= 10 and total_amount_of_purchases >= 100000:
  grade = 'VIP'
  price_item -= (price_item * 0.1)
elif number_of_purchases >= 1:
  grade = 'Family'
  price_item -= (price_item * 0.05)
else:
  grade = 'Non-member'

print(f'{grade}, {price_item}')

VIP, 4500.0


In [ ]:
# 연습문제 5
name = 'Jay'
sex = 'M'
age = 27
height = 180.3
weight = 65.5

if age >= 18:
  status = '성인'
  if sex == 'M':
    sex = '남성'
  else:
    sex = '여성'
else:
  status = '어린이'
  if sex == 'M':
    sex = '남성'
  else:
    sex = '여성'

h = height * 0.01
bmi = np.round(weight / (h * h),2)
if bmi >= 25:
  result_bmi = '비만'
elif bmi > 18.5:
  result_bmi = '저체중'
else:
  result_bmi = '정상체중'

In [ ]:
print(f'환자의 이름은 {name}입니다. {age}세의 ({status + sex})이며, 키는 ({height}), 몸무게는 ({weight})로, BMI 지수는 ({bmi}))이며 ({result_bmi})입니다.')

환자의 이름은 Jay입니다. 27세의 (성인남성)이며, 키는 (180.3), 몸무게는 (65.5)로, BMI 지수는 (20.15))이며 (저체중)입니다.


In [ ]:
# 연습문제 6
a,b,c,d = 93, 54, 65, 68

avg = a+b+c+d//4

if avg >= 70:
  if a < 60 or b < 60 or c < 60 or d < 60:
    result = '불합'
  else:
    result = '합'
else:
    result = '불합'

print(result)

불합


# 3.7 고급 데이터 타입

In [ ]:
# 연습문제 1
names = ['nct', 'nct127', 'nctdream', 'wayv']
s = names
print(len(s))

if s == names:
  print('All of objects refer to same list.')
else:
  print('error')

4
All of objects refer to same list.


In [ ]:
# 연습문제 2
weight = [49.5, 52, 47]
max = weight[0]
for i in range(3):
  if max < weight[i]:
    max = weight[i]

print(max)

52


In [ ]:
# 연습문제 3
customer = [{'Name' : 'Yujeong','Tel' : 9787, 'Price':18},
            {'Name' : 'Jaehyun','Tel' : 1997, 'Price':214},
            {'Name' : 'Taeil','Tel' : 1994, 'Price':614},
            {'Name' : 'Haechan','Tel' : 2000, 'Price':66}]

In [ ]:
for i in range(4):
  if customer[i]['Price'] >= 50:
    print(customer[i])

{'Name': 'Jaehyun', 'Tel': 1997, 'Price': 214}
{'Name': 'Taeil', 'Tel': 1994, 'Price': 614}
{'Name': 'Haechan', 'Tel': 2000, 'Price': 66}


In [ ]:
# 연습문제 4
dict_list = [] # 빈 리스트 생성

dict1 = {'KO' : '사랑', 'EN' : 'Love', 'JP' : '愛'}
dict2 = {'KO' : '집', 'EN' : 'House', 'JP' : '家'}
dict3 = {'KO' : '바다', 'EN' : 'Sea', 'JP' : '海'}
dict4 = {'KO' : '행복', 'EN' : 'Happiness', 'JP' : '幸せ'}

dict_list = [dict1, dict2, dict3, dict4]

In [ ]:
dict_list[-1]['EN']

'Happiness'

In [ ]:
# 연습문제 5
import numpy as np

lot_answer = list(0 for i in range(6))
lot_me = list(0 for i in range(6))
cnt = 0

for i in range(6):
  lot_answer[i] = np.random.randint(1,46)
  lot_me[i] = np.random.randint(1,46)
  if lot_answer[i] == lot_me[i]:
    cnt += 1

print(lot_answer)
print(lot_me)
print(cnt)

[38, 29, 30, 35, 39, 35]
[23, 17, 6, 44, 39, 40]
1


# 3.8 반복문


In [ ]:
# 연습문제 1
n = int(input())
cnt = 0

while n != 1:
  if n%2 == 0:
    n /= 2
  else:
    n = n * 3 + 1
  print(n)
  cnt += 1

print(f'콜라츠 추측이 {cnt}번 만에 성립함이 확인되었다요')

5
16
8.0
4.0
2.0
1.0
콜라츠 추측이 5번 만에 성립함이 확인되었다요


In [ ]:
# 연습문제 2
my_list = ['Yujeong', 'Heejin', 'Sunbun', 'Hyunung','Minjeong','Haeyoung']
cnt = 0
for i in my_list:
  cnt += 1
print(f'my_list에는 {cnt}명이 저장되어 있음')

my_list에는 6명이 저장되어 있음


In [ ]:
# 연습문제 3
cnt = 0
while cnt != 5:
  print(f'{cnt+1}) Hi, Everybody!')
  cnt += 1

for i in range(6, 11):
  print(f'{i}) Hi, Everybody!')


1) Hi, Everybody!
2) Hi, Everybody!
3) Hi, Everybody!
4) Hi, Everybody!
5) Hi, Everybody!
6) Hi, Everybody!
7) Hi, Everybody!
8) Hi, Everybody!
9) Hi, Everybody!
10) Hi, Everybody!


In [ ]:
# 연습문제 4
x = 0
max = 1

while (5*(x**3)+2*(x**2)-19*x+20) <= 20000:
  if max < x:
    max = x
  x += 1

print(x)

16


In [ ]:
# 연습문제 5
weight = [0 for i in range(12)]

for i in range(12):
  weight[i] = np.random.randint(43, 53)
  print(weight[i], end=' ')

50 43 52 50 48 52 50 49 49 48 43 47 

In [ ]:
avg, max = 0, 0
min = weight[0]
for i in range(12):
  avg += weight[i]
  if max < weight[i]:
    max = weight[i]
  if min > weight[i]:
    min = weight[i]

print(np.round(avg/12, 2), min, max)

48.42 43 52


In [ ]:
print(f'평균 = {np.round(np.mean(weight),2)}, 최소 = {np.min(weight)} - {np.argmin(weight)+1}월, 최대 = {np.max(weight)} - {np.argmax(weight)+1}월')

평균 = 48.42, 최소 = 43 - 2월, 최대 = 52 - 3월


In [ ]:
# 연습문제 6
customer = [{'Name' : 'Yujeong','Tel' : 9787, 'Price':18},
            {'Name' : 'Jaehyun','Tel' : 1997, 'Price':214},
            {'Name' : 'Taeil','Tel' : 1994, 'Price':614},
            {'Name' : 'Haechan','Tel' : 2000, 'Price':66}]

for c in customer:
  if c['Price'] > 50:
    print(c)

{'Name': 'Jaehyun', 'Tel': 1997, 'Price': 214}
{'Name': 'Taeil', 'Tel': 1994, 'Price': 614}
{'Name': 'Haechan', 'Tel': 2000, 'Price': 66}


In [ ]:
# 연습문제 7
# == 3.7절 연습문제 5

# 3.9 Numpy 배열

In [ ]:
# 연습문제 1
np.random.rand(5,7)

array([[0.28759591, 0.9665793 , 0.63154862, 0.31154253, 0.92883053,
        0.23468646, 0.64605437],
       [0.1810001 , 0.68368548, 0.2268074 , 0.76948586, 0.4318478 ,
        0.22340669, 0.44505534],
       [0.66793332, 0.53862606, 0.75324567, 0.74993468, 0.99961891,
        0.08429107, 0.83430027],
       [0.80878289, 0.44215133, 0.65097547, 0.96935856, 0.8467673 ,
        0.77311395, 0.61643534],
       [0.13463138, 0.5127886 , 0.86371911, 0.31159464, 0.31577817,
        0.59193692, 0.64294132]])

In [ ]:
# 연습문제 2
n = np.zeros((3,4,5))
n.shape

(3, 4, 5)

In [ ]:
n

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
# 연습문제 3
np.array([1,4,5,95,74,2])

array([ 1,  4,  5, 95, 74,  2])

In [ ]:
# 연습문제 4
n = np.random.rand(45)
m = n.reshape(9,5)
m.shape

(9, 5)

In [ ]:
# 연습문제 5
m = np.expand_dims(m,-1)
m.shape

(9, 5, 1)

In [ ]:
# 연습문제 6
import numpy as np

In [ ]:
data = np.array([[8.5, 200, 60.2, 450.3, 50],
                 [12.3, 230.5, 56.3, 390.2, 35],
                 [9.2, 190, 30, 500.4, 60]])

In [ ]:
data[:,2] >= 40

array([ True,  True, False])

In [ ]:
data[data[:,2] >= 40, -1].mean()

42.5

In [ ]:
# 연습문제 7
data[:,3] >= 400

array([ True, False,  True])

In [ ]:
data[data[:,3]>=400,3] = 400

In [ ]:
data

array([[  8.5, 200. ,  60.2, 400. ,  50. ],
       [ 12.3, 230.5,  56.3, 390.2,  35. ],
       [  9.2, 190. ,  30. , 400. ,  60. ]])

# 3.10 사용자 정의 함수

In [ ]:
# 연습문제 1
def bmi(w, h):
  h *= 0.01
  return w / (h * h)

In [ ]:
w = 49.5
h = 152
print(f'bmi = {bmi(w,h):.2f}')

bmi = 21.42


In [ ]:
# 연습문제 2
def walk(n):
  avg_walk = np.round(n.mean(),2)
  min_day = n.argmin()
  min_walk = n[min_day]
  max_day = n.argmax()
  max_walk = n[max_day]
  return avg_walk, min_day, min_walk, max_day, max_walk

In [ ]:
me = np.round(np.random.rand(30) * 10000)
print(me)

walk(me)

[4125. 7202. 7671. 4506. 7374. 9520. 4084. 5958. 7269. 4524. 9793. 6534.
  957. 3956. 7783. 4663. 8415. 1148. 3959. 8404. 9688. 9375. 3265.  214.
 7855. 4298. 5998. 6468. 1995. 2686.]


(5656.23, 23, 214.0, 10, 9793.0)

In [ ]:
# 연습문제 3
import math
def calc_math(a,b,c):
  try:
    x1 = (-b + math.sqrt(b**2 - 4*a*c)) / 2*a
    x2 = (-b - math.sqrt(b**2 - 4*a*c)) / 2*a
    return x1, x2
  except:
    print('Error')

def calc_non(a,b,c):
  n = b**2 - 4*a*c
  if n > 0:
    x1 = np.round((-b + n**0.5) / 2*a)
    x2 = np.round((-b - n**0.5) / 2*a)
    print(x1, ',', x2)
  elif n == 0:
    x = np.round(-b / 2*a)
    print(x, '중근')
  else:
    print('허근')


In [ ]:
a,b,c = list(map(int, input().split()))

1 4 -21


In [ ]:
calc_math(a,b,c)

(3.0, -7.0)

In [ ]:
calc_non(a,b,c)

-7.0 , 3.0


In [ ]:
# 연습문제 4
def find_point(a,b,c,d):
  return 0

In [ ]:
# 연습문제 5
def len_arr(arr):
  col = arr.shape[0]
  row = arr.shape[1]
  print(f'col-{col}, row-{row}')


In [ ]:
arr = np.array(np.random.rand(3,4))
len_arr(arr)

col-3, row-4


In [ ]:
# 연습문제 6
def book_info(t,y,a,p):
  book = {}
  book = {'Title':t, 'Year':y, 'Author':a, 'Price':p}
  return book

In [ ]:
book_info('It''s your Birthday', 1997, 'thangyou', 31400)

{'Title': 'Its your Birthday',
 'Year': 1997,
 'Author': 'thangyou',
 'Price': 31400}