**Chapter 5. 딥러닝의 개념**


5.2 네트워크의 입력과 출력을 위한 데이터의 변환

# 범주형 데이터의 수치화

In [ ]:
sex = ['male', 'male','female','male','female','female']

In [ ]:
import numpy as np
sex_conv = np.zeros(6)    # numpy배열을 만들고, 0으로 초기화
cnt = 0                   # 위치를 지정할 인덱스 변수의 값
for x in sex:             # 성별 리스트의 전체 데이터에 대해 반복
  if(x == 'female'):      # 해당 항목의 값이 female 이라면
    sex_conv[cnt] = 1     # 숫자 데이터의 값을 1로 변경
  cnt = cnt +1            # 인덱스 변수의 값을 1 증가시킴

In [ ]:
# tensorflow.keras.utils 모듈의 to_categorical 함수 import
from tensorflow.keras.utils import to_categorical
# one-hot-encoding 적용
sex_cate = to_categorical(sex_conv)

In [ ]:
print(sex_cate)

[[1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]]


# 수치로 된 범주형 데이터의 원-핫-인코딩


In [ ]:
pclass_orig = np.array([3,1,2,1,2,3])

In [ ]:
# tensorflow.keras.utils 모듈의 to_categorical 함수 import
from tensorflow.keras.utils import to_categorical
# (0,1,2의 값을 가지도록) 1을 뺀 후, one-hot-encoding 적용.
pclass_cate = to_categorical(pclass_orig-1)

In [ ]:
print(pclass_cate)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 수치형 데이터의 정규화

In [ ]:
import numpy as np # numpy 라이브러리를 np라는 이름으로 사용한다.
age_orig = np.array([3,28,21,67,80,53]) # numpy 배열을 만들고 각각의 값을 지정한다.
age_conv = (age_orig - 3) / (80 - 3) # 0과 1 범위의 값으로 변환한다.
        # (원데이터 - 최솟값) / (최댓값 - 최솟값)

In [ ]:
age_conv = (age_orig - np.min(age_orig)) / (np.max(age_orig) - np.min(age_orig))

In [ ]:
print(age_conv)

[0.         0.32467532 0.23376623 0.83116883 1.         0.64935065]
